### ISSUE TITLE
revision not found

### ISSUE THREAD

**Issue by mercuryglory** [MoKee/android_frameworks_base#23]
Syncing work tree:  54% (388/717)error: in `sync -f -j4`: revision refs/heads/mkp in MoKee/android_frameworks_base not found

**Comment by martincz** [comment]
https://github.com/MoKee/android_frameworks_base/tree/mkp
It's exists, have you use a mirror?

**Comment by mercuryglory** [comment]
Yes,I used `repo init -u https://github.com/MoKee/android -b mkp` and tsinghua mirror to replace google source.After sync finished I used `. build/envsetup.sh` and 'lunch', then the problem above appeared.I have used branch mko-mr1 to replace. My target device is Redmi Note5, whyred

**Comment by kkyflying** [comment]
hi. l hava the same problem , l don't hava finish the sync work, always following this error  
```
Checking out projects:  50% (378/756) platform/external/zxingerror: Cannot checkout MoKee/android_frameworks_base: ManifestInvalidRevisionError: revision refs/heads/mkq-mr1 in MoKee/android_frameworks_base not found
error: in `sync`: revision refs/heads/mkq-mr1 in MoKee/android_frameworks_base not found
```
please help me ,thx~

**Comment by martincz** [comment]
https://github.com/MoKee/android_frameworks_base/branches
but branch already in here.
If you can sync, you should check your repo tools or contact Github.

**Comment by kkyflying** [comment]
thank you , l try again~~
